name: smartcoiha-backend
services:
  smartcoiha-api:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: smartcoiha_api
      ports:
        - "5000:8080"
      environment:
        ASPNETCORE_ENVIRONMENT: Development
        ASPNETCORE_URLS: http://+:8080
        ConnectionStrings__DefaultConnection: Host=smartcoiha-db;Port=5432;Database=SMARTCoIHA_DB;Username=admin;Password=pgadmin123
        ConnectionStrings__Redis: smartcoiha-cache:6379
        AppSettings__FrontendUrl: http://localhost:3000
      depends_on:
        - smartcoiha-db
        - smartcoiha-cache
        - smartcoiha-mq
  smartcoiha-db:
    image: postgres:latest
    container_name: smartcoiha-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pgadmin123
      POSTGRES_DB: SMARTCoIHA_DB
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  smartcoiha-cache: 
    image: redis:latest
    container_name: smartcoiha_redis
    ports:
      - "6379:6379"

  smartcoiha-mq: 
    image: rabbitmq:3-management
    container_name: smartcoiha_rabbitmq
    ports: 
      - "5672:5672" #Rabbit mq port
      - "15672:15672" #Management UI Port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: GUEST  

volumes:
  postgres_data:

