// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence.Data;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260307161951_UpdatedEntities")]
    partial class UpdatedEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.DataRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiryTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("FingerprintValidationSuccess")
                        .HasColumnType("boolean");

                    b.Property<string>("InstitutePatientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InstitutionApprovedStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RequestedTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RequestingInstitutionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataRequests");
                });

            modelBuilder.Entity("Domain.Entities.FhirResourceStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<Guid>("InsituteBaseUrlId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InstituteBaseUrlId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("ResourceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InstituteBaseUrlId");

                    b.ToTable("FhirResourceStatus");
                });

            modelBuilder.Entity("Domain.Entities.InstituteBaserUrl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("InstitutionID")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VerificationStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionID");

                    b.ToTable("FHIREndpoints");
                });

            modelBuilder.Entity("Domain.Entities.Institution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegistrationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VerificationStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Institutions");
                });

            modelBuilder.Entity("Domain.Entities.Patients", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EnrollmentStatus")
                        .HasColumnType("integer");

                    b.Property<string>("FingerPrint")
                        .HasColumnType("text");

                    b.Property<string>("InstitutePatientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("InstitutionID")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("InstitutionID");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Domain.Entities.FhirResourceStatus", b =>
                {
                    b.HasOne("Domain.Entities.InstituteBaserUrl", "InstituteBaseUrl")
                        .WithMany("ResourceStatuses")
                        .HasForeignKey("InstituteBaseUrlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InstituteBaseUrl");
                });

            modelBuilder.Entity("Domain.Entities.InstituteBaserUrl", b =>
                {
                    b.HasOne("Domain.Entities.Institution", "Institution")
                        .WithMany("FhirEndpoints")
                        .HasForeignKey("InstitutionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("Domain.Entities.Patients", b =>
                {
                    b.HasOne("Domain.Entities.Institution", "Institution")
                        .WithMany()
                        .HasForeignKey("InstitutionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("Domain.Entities.InstituteBaserUrl", b =>
                {
                    b.Navigation("ResourceStatuses");
                });

            modelBuilder.Entity("Domain.Entities.Institution", b =>
                {
                    b.Navigation("FhirEndpoints");
                });
#pragma warning restore 612, 618
        }
    }
}
